name: Deploy on push to staging server deploy

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: testdeepak.7searchppc.in
        username: admin_testdeepak
        password: sga*gO#@9cHsKghJ
        server-dir: '/public_html/'
        port: 21
        protocol: ftps
